// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvaoqqdhxsvzcejwyzkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2YW9xcWRoeHN2emNland5emt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NzAwNjQsImV4cCI6MjA5MTI0NjA2NH0.PWBdRP_xisaG1D0Ugd5IB6k8wFQza3Zel3DddJm-FVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});